---
- name: Set Hostname with hostname command
  hostname:
    name: "{{ hostname }}"
  notify:
    - restart hostname
    - restart systemd-logind

- name: Re-gather facts
  action: setup
  when: ansible_hostname != fqdn

- name: Build hosts file (backups will be made)
  lineinfile:
    dest: /etc/hosts
    # hostname is a better anchor
    regexp: "{{ hostname }}"
    line: "{{ ip_address }} {{ fqdn }} {{ hostname }}"
    state: present
    # # needed for "hostname -f" to return the fqdn
    # # https://manpages.debian.org/stretch/hostname/domainname.1.en.html#THE_FQDN
    # insertbefore: BOF
    backup: yes
  when: ip_address is defined
  notify:
    - restart hostname
    - restart systemd-logind
